org.gradle.jvmargs=-Xmx2G
modName=MoogsOceanStructures
minecraftVersion=1.21
modVersion=1.0.0
modId=mos
modDescription=Moog's Ocean Structures
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mos-moogs-ocean-structures
modSources=https://github.com/FinnSetchell/Moog-s-Ocean-Structures
modReleases=https://github.com/FinnSetchell/Moog-s-Ocean-Structures/releases
modIssues=https://github.com/FinnSetchell/Moog-s-Ocean-Structures/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/mos-moogs-ocean-structures
modModrinth=https://modrinth.com/mod/mos-moogs-ocean-structures

structureLibVersionRange=[1.0.0,)

publishDisplayPrefix=MOS
publishDisplaySuffix=[UNIVERSAL]

# TODO: replace placeholders once Modrinth + CurseForge projects are created
modrinthProjectId=TODO_MODRINTH_ID
curseforgeProjectId=000000
curseforgeProjectSlug=mos-moogs-ocean-structures
modrinthProjectSlug=mos-moogs-ocean-structures
publishMcStart=1.21
publishMcEnd=1.21.11
publishExtraMcVersions=26.1,26.1.1,26.1.2

discordAvatarUrl=
discordEmbedColor=#1e5fa8
discordThumbnailUrl=
discordRoleId=1466012771379581039
discordPing=true

# Release type: major | minor | alpha
# major  -> #announcements + @mod-announcements ping (if discordPing=true)
# minor  -> #minor-builds + @minor-mod-announcements ping (if discordPing=true)
# alpha  -> #test-builds + @play-test-volunteer ping (if discordPing=true)
releaseType=minor
